version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3 # L'image exacte de ton projet
    container_name: traveling_db_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: traveling_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: